export const INLINE_KEYBOARD_ID_ADMIN = {
  SUBMIT_CREATE_CLIENT: "SUBMIT_CREATE_CLIENT",
  DELETE_CLIENT: "DELETE_CLIENT",
  CANCEL_CREATE_CLIENT: "CANCEL_CREATE_CLIENT",
  SUBMIT_DELETE_CLIENT: "SUBMIT_DELETE_CLIENT",
  CANCEL_DELETE_CLIENT: "CANCEL_DELETE_CLIENT",
  SUBMIT_TASK: "SUBMIT_TASK",
  SUBMIT_COMPLETE_TASK: "SUBMIT_COMPLETE_TASK",
  CANCEL_COMPLETE_TASK: "CANCEL_COMPLETE_TASK",
  PREVIOUS: "PREVIOUS",
  NEXT: "NEXT",
  CLIENTS_PREVIOUS: "CLIENTS_PREVIOUS",
  CLIENTS_NEXT: "CLIENTS_NEXT",
};
export const INLINE_KEYBOARD_ID_CLIENT = {
  CANCEL_CREATE_TASK: "CANCEL_CREATE_TASK",
  SUBMIT_CREATE_TASK: "SUBMIT_CREATE_TASK",
};
